# Generated by Django 5.2.7 on 2025-11-09 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0006_alter_blogsettings_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="summary",
            field=models.TextField(
                blank=True,
                help_text="文章摘要，为空时将自动从内容生成",
                null=True,
                verbose_name="summary",
            ),
        ),
    ]
